<div class = "left details-left">
    <h1>Device details: <?php echo $this->_vars->device->get_name() ?></h1>

    <table class = "object-details" cellspacing = "1" cellpadding = "1" align = "left">
        <tr>
            <td class = "label">
                ID:
            </td>
            <td>
                <?php echo $this->_vars->device->get_main_id() ?>
            </td>
        </tr>
        <tr>
            <td class = "label">
                Name:
            </td>
            <td>
                <?php echo $this->_vars->device->get_name() ?>
            </td>
        </tr>
        <tr>
            <td class = "label">
                Address IP v4:
            </td>
            <td>
                <?php echo $this->_vars->device->get_address() ?>
            </td>
        </tr>
        <tr>
            <td class = "label">
                Address IP v6:
            </td>
            <td>
                <?php echo $this->_vars->device->get_address6() ?>
            </td>
        </tr>
        <tr>
            <td class = "label">
                Added time:
            </td>
            <td>
                <?php echo $this->_vars->device->get_added_time()->get_date('H:i:s d-m-Y') ?>
            </td>
        </tr>
    </table>
</div>
<div class ="left details-right">
    <h2>History:</h2>
    <?php if(count($this->_vars->history) == 0) : ?>
    <p>There are no history for this device</p>
    
    <?php else: ?>
    <table class = "object-details" cellspacing = "1" cellpadding = "1" align = "left">
        <?php foreach($this->_vars->history as $history) : ?>
        <tbody>
            <tr>
                <td class = "label">
                    ID:
                </td>
                <td>
                    <?php echo $history->id ?>
                </td>
            </tr>
            <tr>
                <td class = "label">
                    Name:
                </td>
                <td>
                    <?php echo $history->name ?>
                </td>
            </tr>
            <tr>
                <td class = "label">
                    Address IP v4:
                </td>
                <td>
                    <?php echo $history->address ?>
                </td>
            </tr>
            <tr>
                <td class = "label">
                    Address IP v6:
                </td>
                <td>
                    <?php echo $history->address6 ?>
                </td>
            </tr>
            <tr>
                <td class = "label">
                    Modify time:
                </td>
                <td>
                    <?php echo $history->added_time->get_date('H:i:s d-m-Y') ?>
                </td>
            </tr>
        </tbody>
    <?php endforeach;?>
    </table>
    <?php endif; ?>
</div>
<div class = "clear"></div>