<!DOCTYPE xhtml>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel = "Stylesheet" type = "text/css" href = "css/nmonit.css" />
        <link rel = "Stylesheet" type = "text/css" href = "css/index.css" />
        <meta http-equiv="refresh" content="5"> 
    </head>
    <body>
        <div id = "main">
            <div id = "header">
                <noscript>
                    <h1>Please enable javascript</h1>
                </noscript>
                <div class = "left">
                    <div id = "header-title">NMonit</div>
                    <div id = "header-desc">Network activity logger of programs for system Linux</div>
                </div>
                <div class = "left">
                    <div id ="header-menu">
                        <a href = "?action=index">Summary</a>
                        &nbsp;|&nbsp;
                        <a href = "?action=objects">Objects info</a>
                    </div>
                </div>
                <div class = "clear"></div>
            </div>
            <div class = "clear"></div>
            <div id = "content">
            
                <h1>To the database are saved new information. Please wait a while...</h1>
                <p>Page will be automatically refresh after 5 seconds</p>
                
            </div>
        </div>
    </body>
</html>

        
        