<div id = "objects_content">
    <p>Sort by: </p>
    &raquo; <a href = "?action=objects&task=list&object=devices">Name: from A to Z</a> <br />
    &raquo; <a href = "?action=objects&task=list&object=devices&desc=1">Name: from Z to A</a> <br />
    &raquo; <a href = "?action=objects&task=list&object=devices&order=usage">Network usage: ascending</a> <br />
    &raquo; <a href = "?action=objects&task=list&object=devices&order=usage&desc=1">Network usage: descending</a>
    <br /><br />
    <table class = "objects-list devices" border = "0" cellspacing = "0" cellpadding = "0">
        <tr>
            <th class = "object-list-id">
                ID
            </th>
            <th>
                Name
            </th>
            <th class = "object-list-address">
                Address IP v4
            </th>
            <th class = "object-list-address6">
                Address IP v6
            </th>
            <th class = "object-list-details">
                Details
            </th>
        </tr>
        <?php foreach($this->_vars->devices as $device) : ?>
        <tr>
            <td>
                <?php echo $device['master_id'] ?>
            </td>
            <td>
                <?php echo $device['name'] ?>
            </td>
            <td>
                <?php echo $device['address'] ?>
            </td>
            <td>
                <?php echo $device['address6'] ?>
            </td>
            <td>
                <a href = "?action=objects&amp;task=details&amp;object=program&amp;id=<?php echo $device['master_id'] ?>">Details</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>